[package]
name = "dcap-qvl-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dcap-qvl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
dcap-qvl = { path = "../", features = ["report"] }
hex = "0.4.3"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
